[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
]

[fmt]
single_line_statement_blocks = "single"
multiline_func_header = "params_first"
contract_new_lines = true
number_underscore = "preserve"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config